var StrNav ="";
StrNav+='<a class="navbar-brand" href="index.html">好的交易</a>';
StrNav+='		 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
StrNav+='			<span class="navbar-toggler-icon"></span>';
StrNav+='		 </button>';
StrNav+='        <div class="collapse navbar-collapse" id="navbarSupportedContent">';
StrNav+='            <ul class="navbar-nav mr-auto">';
StrNav+='                <li class="nav-item dropdown">';
StrNav+='                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
StrNav+='                        世界經濟';
StrNav+='                   </a>';
StrNav+='                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">';
StrNav+='                        <a class="dropdown-item" href="#">美國大盤</a>';
StrNav+='                        <a class="dropdown-item" href="#">各國大盤</a>';
StrNav+='                        <div class="dropdown-divider"></div>';
StrNav+='                        <a class="dropdown-item" href="#">經濟數據</a>';
StrNav+='                    </div>';
StrNav+='                </li>';
StrNav+='                <li class="nav-item dropdown">';
StrNav+='                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
StrNav+='                        世界農產品';
StrNav+='                   </a>';
StrNav+='                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">';
StrNav+='                        <a class="dropdown-item" href="soyBean.html">黃豆</a>';
StrNav+='                    </div>';
StrNav+='                </li>';
StrNav+='                <li class="nav-item dropdown">';
StrNav+='                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
StrNav+='                        台灣經濟';
StrNav+='                   </a>';
StrNav+='                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">';
StrNav+='                        <a class="dropdown-item" href="#">大盤</a>';
StrNav+='                        <a class="dropdown-item" href="#">景氣燈號</a>';
StrNav+='                        <a class="dropdown-item" href="#">數據資料</a>';
StrNav+='                    </div>';
StrNav+='                </li>';
StrNav+='                <li class="nav-item">';
StrNav+='                    <a class="nav-link" href="#">房市</a>';
StrNav+='                </li>';
StrNav+='                <li class="nav-item">';
StrNav+='                    <a class="nav-link" href="#">彼特幣</a>';
StrNav+='                </li>';
StrNav+='                <li class="nav-item">';
StrNav+='                    <a class="nav-link" href="#">經濟學</a>';
StrNav+='                </li>';
StrNav+='                <li class="nav-item">';
StrNav+='                    <a class="nav-link" href="#">會計學</a>';
StrNav+='                </li>';
StrNav+='            </ul>';
StrNav+='            <form class="form-inline my-2 my-lg-0">';
StrNav+='                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">';
StrNav+='                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>';
StrNav+='            </form>';
StrNav+='        </div>';

$('#myNav').append(StrNav);